In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [7]:
dataset = pd.read_csv("../datasets/diamonds.csv")
data = dataset.loc[:,['carat', 'depth', 'table', 'cut', 'price']]
print(data.head(20))

    carat  depth     x  price
0    0.23   61.5  3.95    326
1    0.21   59.8  3.89    326
2    0.23   56.9  4.05    327
3    0.29   62.4  4.20    334
4    0.31   63.3  4.34    335
5    0.24   62.8  3.94    336
6    0.24   62.3  3.95    336
7    0.26   61.9  4.07    337
8    0.22   65.1  3.87    337
9    0.23   59.4  4.00    338
10   0.30   64.0  4.25    339
11   0.23   62.8  3.93    340
12   0.22   60.4  3.88    342
13   0.31   62.2  4.35    344
14   0.20   60.2  3.79    345
15   0.32   60.9  4.38    345
16   0.30   62.0  4.31    348
17   0.30   63.4  4.23    351
18   0.30   63.8  4.23    351
19   0.30   62.7  4.21    351


In [8]:
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

In [9]:
print(X)
print(y)

[[ 0.23 61.5   3.95]
 [ 0.21 59.8   3.89]
 [ 0.23 56.9   4.05]
 ...
 [ 0.71 60.5   5.79]
 [ 0.71 59.8   5.74]
 [ 0.7  60.5   5.71]]
[ 326  326  327 ... 2756 2756 2757]


In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X[:5])
scaler = MinMaxScaler(feature_range=(0, 1))
scaler.fit(X)
scaled_X = scaler.transform(X)
print(scaled_X[:5])

IndexError: tuple index out of range