In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv("../datasets/diamonds.csv")
data = dataset.loc[:,['carat', 'depth', 'table', 'cut', 'price']]
print(data.head(20))

FileNotFoundError: [Errno 2] No such file or directory: 'datasets/diamonds.csv'

In [ ]:
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

In [ ]:
print(X)
print(y)

[[ 0.23 61.5   3.95]
 [ 0.21 59.8   3.89]
 [ 0.23 56.9   4.05]
 ...
 [ 0.71 60.5   5.79]
 [ 0.71 59.8   5.74]
 [ 0.7  60.5   5.71]]
[ 326  326  327 ... 2756 2756 2757]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X[:5])
scaler = MinMaxScaler(feature_range=(0, 1))
scaler.fit(X)
scaled_X = scaler.transform(X)
print(scaled_X[:5])

IndexError: tuple index out of range